site_name: To awk or not
nav:
  - Home: index.md
  - 1.Simple examples: 1.Simple_example.md
  - 2.Tesing with grep: 2.Teasing_with_grep.md
  - 3.Shell we awk: 3.Shell_we_awk.md
  - 4.Brief commands: 4.Brief_commands.md
  - 5.String manipulation: 5.String_manipulation.md
  - 6.One line programs: 6.One_line_programs.md
  - Python vs. awk: Python_vs_awk.md
  - Exercises:
    - Warming up: Exercises/Exercises.md
    - 01.Simple arithmetic *: Exercises/01.Simple_arithmetic.md
    - 02.Data extraction *: Exercises/02.Data_extraction.md
    - 03.Data extraction **: Exercises/03.Data_extraction.md
    - 04.Data manipulation **: Exercises/04.Data_manipulation.md
    - 05.Easy tricks *: Exercises/05.Easy_tricks.md
    - 06.Bioinformaticians corner *: Exercises/06.Bioinformaticians_corner.md
    - Advanced data analysis ****: Exercises/Advanced_data_analysis.md
    - Carpool ***: Exercises/Carpool.md
    - Difficult to extract data ****: Exercises/Dificult_data.md
    - Scrubing a web page **: Exercises/Scrubbing.md
    - String manipulation **: Exercises/String_manipulation.md
    - Simple linear regresion ***: Exercises/Linear_regression.md
  - "= Case Studies =": Case_studies/List.md
  - Fixed size fields: Other/Fixed_size_fields.md
  - Backreferences: Other/Backreferences.md
  - Multii-Line records: https://www.gnu.org/software/gawk/manual/html_node/Multiple-Line.html
  - Localization problems: Other/Localization.md
  - Awk vs. nawk vs. gawk: http://www.thegeekstuff.com/2011/06/awk-nawk-gawk/
  - GitHub & Binder: Other/Binder.md
  - About: About.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  - footnotes
  - attr_list
  - def_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
features:
  - search.highlight
repo_url: https://github.com/pmitev/to-awk-or-not
#theme: readthedocs
